name: amlm-env
channels:
  - conda-forge
dependencies:
  # Python estable para OpenCV
  - python=3.11

  # Núcleo científico
  - numpy
  - pandas
  - matplotlib

  # Visión por computadora
  - opencv

  # Jupyter
  - jupyterlab
  - ipykernel

  # Utilidades
  - pip

  # (Opcional) si luego trabajas con imágenes más avanzadas
  # - scikit-image
